######################## default configuration ####################
baseURL = "https://another-future-entirely.onrender.com"
title = "Another Future Entirely"
theme = "somrat"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # disable language from here
# google analutics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com


############################# Outputs ##############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe= true
hardWraps = false
xhtml = false

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
[[params.plugins.css]]
link = "plugins/baguetteBox/baguetteBox.min.css"



# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"
[[params.plugins.js]]
link = "plugins/baguetteBox/baguetteBox.min.js"


#################### default parameters ################################
[params]
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Nejc Trampuž"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.


################################### English language #####################################
[Languages.en]
languageName = ":flag_gb:"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# english navigation ##################

# main menu
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
pre = "#"
url = "video-presentation"
weight = 2

[[Languages.en.menu.main]]
name = "Book"
pre = "#"
url = "book"
weight = 5

[[Languages.en.menu.main]]
name = "Team"
pre = "#"
url = "team"
weight = 6

[[Languages.en.menu.main]]
name = "Info"
pre = "#"
url = "project-exhibitions"
weight = 7



################################### Slovene language #####################################
[Languages.slo]
languageName = ":flag_si:"
languageCode = "slo-slo"
contentDir = "content/slovenia"
weight = 1
home = "Domov"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# english navigation ##################

# main menu
[[Languages.slo.menu.main]]
name = "Domov"
url = "/slo/"
weight = 1

[[Languages.slo.menu.main]]
name = "Video predstavitev"
pre = "/slo/#"
url = "video-presentation"
weight = 2

[[Languages.slo.menu.main]]
name = "O projektu"
pre = "/slo/#"
url = "about"
weight = 3

[[Languages.slo.menu.main]]
name = "Dialogi"
pre = "/slo/#"
url = "dialogs"
weight = 4

[[Languages.slo.menu.main]]
name = "Knjiga"
pre = "/slo/#"
url = "book"
weight = 5

[[Languages.slo.menu.main]]
name = "Ekipa"
pre = "/slo/#"
url = "team"
weight = 6

[[Languages.slo.menu.main]]
name = "Project Exhibitions"
pre = "/slo/#"
url = "project-exhibitions"
weight = 7

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 90
  resampleFilter = 'Box'
